"""
Django settings for web_rigging_program project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import sys
from pathlib import Path
import os
import environ
import dj_database_url
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#Directory to design data
RIGGING_DATA_DIR = BASE_DIR / "data"

env = environ.Env(
    DJANGO_DEBUG = (bool, False),
    CONN_MAX_AGE = (int, 60)
)

DJANGO_ENV = os.environ.get('DJANGO_ENV', 'dev').lower()

env_file = BASE_DIR / (".env.test" if DJANGO_ENV == "test" else ".env")
if env_file.exists():
    environ.Env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

DEBUG = env.bool("DJANGO_DEBUG", default=False)
SECRET_KEY = env("DJANGO_SECRET_KEY", default="")
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost","127.0.0.1", "testserver"])

EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@example.com")

# Anymail (transactional email via HTTP API — avoids SMTP blocking on Railway)
ANYMAIL = {
    "RESEND_API_KEY": env("RESEND_API_KEY", default=""),
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "DEFAULT_PAGINATION_CLASS": (
        "rest_framework.pagination.PageNumberPagination",
    ),
    "PAGE_SIZE": 25,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "EXCEPTION_HANDLER": "apps.api.exceptions.custom_exception_handler"
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'anymail',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'apps.main',
    "rest_framework",
    "corsheaders",
    'apps.api',
    'apps.billing',
    # 'apps.stripe_webhooks',
]

SITE_ID = 1

#Authentication Backends
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

REST_AUTH_REGISTER_SERIALIZERS = {
    "REGISTER_SERIALIZER": "apps.api.v1.auth.serializers.RestrictedRegisterSerializer",
}

# dj-rest-auth JWT Configuration (Modern syntax)
REST_AUTH = {
    'USE_JWT': True,  # Enable JWT authentication
    'JWT_AUTH_COOKIE': 'jwt_token',  # Access token cookie name
    'JWT_AUTH_REFRESH_COOKIE': 'jwt_refresh_token',  # Refresh token cookie
    'JWT_AUTH_HTTPONLY': True,
    'JWT_AUTH_SECURE': not DEBUG,
    "JWT_AUTH_SAMESITE": "Lax",
    'TOKEN_MODEL': None,  # Disable DRF token model completely
    'SESSION_LOGIN': False,  # Don't auto-login after registration (mandatory email verification)
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#Allauth SaaS Configuration
# ACCOUNT_AUTHENTICATION_METHOD = "email" #Deprecated
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# ACCOUNT_EMAIL_REQUIRED = True #Deprecated
# ACCOUNT_USERNAME_REQUIRED = False #Deprecated
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# Frontend URL for email verification redirects
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")

# Redirect URLs for email confirmation (redirects to frontend)
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = f"{FRONTEND_URL}/verify-email"
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = f"{FRONTEND_URL}/verify-email"


MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'web_rigging_program.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_rigging_program.wsgi.application'

# Custom test runner to handle Neon DB connection pooling issues
TEST_RUNNER = 'web_rigging_program.test_runner.NeonTestRunner'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = env("DATABASE_URL", default="")
DATABASE_URL_DIRECT = env("DATABASE_URL_DIRECT", default="")
CONN_MAX_AGE = env.int("CONN_MAX_AGE", default=60)


if DATABASE_URL:
    db_url = DATABASE_URL
    is_testing = "test" in sys.argv

    if is_testing and DATABASE_URL_DIRECT:
        db_url = DATABASE_URL_DIRECT

    DATABASES = {
        "default": dj_database_url.config(
            default=db_url,
            conn_max_age=0 if is_testing else CONN_MAX_AGE,
            conn_health_checks=not is_testing,
        )
    }

    # Additional configuration for test environment to prevent connection pooling issues
    if is_testing:
        DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True
        DATABASES["default"]["ATOMIC_REQUESTS"] = False
        # Only add OPTIONS if using direct connection (not pooler)
        if DATABASE_URL_DIRECT and "pooler" not in db_url.lower():
            DATABASES["default"]["OPTIONS"] = {
                "connect_timeout": 2,
            }
else:
    DATABASES = {
        "default": env.db(
            "DATABASE_URL",
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
        )
    }
    # optional but good for production:
    DATABASES["default"]["CONN_MAX_AGE"] = env.int("CONN_MAX_AGE", default=60)
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication redirects
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Additional CSRF protection
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'

# CORS settings for cookies
CORS_ALLOW_CREDENTIALS = True  # Required for cookies

# Stripe Configuration
STRIPE_API_KEY = env("STRIPE_API_KEY", default="")
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET_LOCAL", default="")

# Stripe Price IDs (managed via .env)
STRIPE_PRICE_STARTER_MONTH = env("STRIPE_PRICE_STARTER_MONTH", default="")
STRIPE_PRICE_STARTER_YEAR = env("STRIPE_PRICE_STARTER_YEAR", default="")
STRIPE_PRICE_PRO_MONTH = env("STRIPE_PRICE_PRO_MONTH", default="")
STRIPE_PRICE_PRO_YEAR = env("STRIPE_PRICE_PRO_YEAR", default="")

# ---------------------------------------------------------------------------
# Logging
# LOG_LEVEL controls the verbosity of the rigging domain loggers.
# Set to DEBUG in .env to see the full pipeline funnel on every computation;
# WARNING (the default) shows only failure diagnostics.
# ---------------------------------------------------------------------------
_LOG_LEVEL = env("LOG_LEVEL", default="WARNING")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        # Rigging domain — captures design.py, selector.py, engine.py, etc.
        "domain.rigging": {
            "handlers": ["console"],
            "level": _LOG_LEVEL,
            "propagate": False,
        },
    },
}
