@analysis_id = 855f75ab-f2b8-4422-bd34-8206b3df94dc
### GET token
POST {{host}}/api/v1/auth/token/
Content-Type: application/json

{
  "username": "{{first_username}}",
  "password": "{{first_password}}"
}

> {%
    client.global.set("access_token", response.body.access);
%}

###
DELETE {{host}}/api/v1/analysis/{{analysis_id}}/
Authorization: Bearer {{access_token}}
