### Registration
POST {{host}}/api/v1/auth/registration/
Content-Type: application/json

{
  "username": "saasuser@example.com",
  "email": "saasuser@example.com",
  "password1": "P@ssword123",
  "password2": "P@ssword123"
}

