### Login
POST {{host}}/api/v1/auth/login/
Content-Type: application/json

{
  "email": "saasuser@example.com",
  "password": "NewStrongPassword#2026"
}

> {%
    client.global.set("access_token", response.body.access);
%}

### Password Change
POST {{host}}/api/v1/auth/password/change/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "new_password1": "NewStrongPassword#2027" ,
  "new_password2": "NewStrongPassword#2027"
}

### Logout
POST {{host}}/api/v1/auth/logout/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{}

### Login New Password
POST {{host}}/api/v1/auth/login/
Content-Type: application/json

{
  "email": "saasuser@example.com",
  "password": "NewStrongPassword#2027"
}

