# Generated by Django 5.1.7 on 2025-05-16 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FibreSling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('construction_type', models.CharField(help_text='Construction type of the sling.', max_length=100)),
                ('material', models.CharField(choices=[('steel', 'Steel'), ('HMPE', 'HMPE'), ('aramid', 'Aramid'), ('other', 'Other')], help_text='Material of the sling.', max_length=100)),
                ('nominal_diameter', models.DecimalField(decimal_places=2, help_text='Nominal diameter in mm.', max_digits=10)),
                ('safety_factor', models.DecimalField(decimal_places=2, help_text='Safety factor.', max_digits=10)),
                ('working_load_limit', models.DecimalField(decimal_places=2, help_text='Working Load Limit in Te.', max_digits=10)),
                ('elongation', models.DecimalField(decimal_places=2, help_text='Elongation percentage.', max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grommet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('construction_type', models.CharField(help_text='Construction type of the sling.', max_length=100)),
                ('material', models.CharField(choices=[('steel', 'Steel'), ('HMPE', 'HMPE'), ('aramid', 'Aramid'), ('other', 'Other')], help_text='Material of the sling.', max_length=100)),
                ('nominal_diameter', models.DecimalField(decimal_places=2, help_text='Nominal diameter in mm.', max_digits=10)),
                ('safety_factor', models.DecimalField(decimal_places=2, help_text='Safety factor.', max_digits=10)),
                ('working_load_limit', models.DecimalField(decimal_places=2, help_text='Working Load Limit in Te.', max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Masterlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('manufacturer', models.CharField(help_text='Manufacturer of the masterlink.', max_length=100)),
                ('model', models.CharField(help_text='Model of the masterlink.', max_length=100)),
                ('working_load_limit', models.DecimalField(decimal_places=2, help_text='Working Load Limit (WLL) of the masterlink in Te.', max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the masterlink in kg.', max_digits=10)),
                ('safety_factor', models.DecimalField(decimal_places=2, help_text='Safety factor of the masterlink.', max_digits=10)),
                ('diameter', models.DecimalField(decimal_places=2, help_text='Diameter of the masterlink in mm.', max_digits=10)),
                ('length_inside', models.DecimalField(decimal_places=2, help_text='Length inside the masterlink in mm.', max_digits=10)),
                ('width_inside', models.DecimalField(decimal_places=2, help_text='Width inside the masterlink in mm.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Masterlink',
                'verbose_name_plural': 'Masterlinks',
                'ordering': ['working_load_limit'],
            },
        ),
        migrations.CreateModel(
            name='MasterlinkAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('manufacturer', models.CharField(help_text='Manufacturer of the masterlink.', max_length=100)),
                ('model', models.CharField(help_text='Model of the masterlink.', max_length=100)),
                ('working_load_limit', models.DecimalField(decimal_places=2, help_text='Working Load Limit (WLL) of the masterlink in Te.', max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the masterlink in kg.', max_digits=10)),
                ('safety_factor', models.DecimalField(decimal_places=2, help_text='Safety factor of the masterlink.', max_digits=10)),
                ('diameter', models.DecimalField(decimal_places=2, help_text='Diameter of the masterlink components in mm.', max_digits=10)),
                ('length_inside', models.DecimalField(decimal_places=2, help_text='Length inside the masterlink in mm.', max_digits=10)),
                ('width_inside', models.DecimalField(decimal_places=2, help_text='Width inside the masterlink in mm.', max_digits=10)),
                ('assembly_diameter', models.DecimalField(decimal_places=2, help_text='Diameter of the assembly in mm.', max_digits=10)),
                ('assembly_length_inside', models.DecimalField(decimal_places=2, help_text='Length inside the assembly in mm.', max_digits=10)),
                ('assembly_width_inside', models.DecimalField(decimal_places=2, help_text='Width inside the assembly in mm.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Masterlink Assemblies',
                'verbose_name_plural': 'Masterlinks Assemblies',
                'ordering': ['working_load_limit'],
            },
        ),
        migrations.CreateModel(
            name='Shackle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('manufacturer', models.CharField(help_text='Manufacturer of the shackle.', max_length=100)),
                ('model', models.CharField(help_text='Model of the shackle.', max_length=100)),
                ('working_load_limit', models.DecimalField(decimal_places=2, help_text='Working Load Limit (WLL) of the shackle in Te.', max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the shackle in kg.', max_digits=10)),
                ('safety_factor', models.DecimalField(decimal_places=2, help_text='Safety factor of the shackle.', max_digits=10)),
                ('inside_width', models.DecimalField(decimal_places=2, help_text='Inside width of the shackle in mm.', max_digits=10)),
                ('inside_length', models.DecimalField(decimal_places=2, help_text='Inside length of the shackle in mm.', max_digits=10)),
                ('bow_width', models.DecimalField(decimal_places=2, help_text='Bow width of the shackle in mm.', max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length of the shackle in mm.', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width of the shackle in mm.', max_digits=10)),
                ('bow_diameter', models.DecimalField(decimal_places=2, help_text='Bow diameter of the shackle in mm.', max_digits=10)),
                ('eye_diameter', models.DecimalField(decimal_places=2, help_text='Eye diameter of the shackle in mm.', max_digits=10)),
                ('pin_diameter', models.DecimalField(decimal_places=2, help_text='Pin diameter of the shackle in mm.', max_digits=10)),
                ('bolt_length', models.DecimalField(decimal_places=2, help_text='Bolt length of the shackle in mm.', max_digits=10)),
                ('tolerance_inside_width', models.DecimalField(blank=True, decimal_places=2, help_text='Tolerance inside width of the shackle in mm.', max_digits=10, null=True)),
                ('tolerance_inside_length', models.DecimalField(blank=True, decimal_places=2, help_text='Tolerance inside length of the shackle in mm.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Shackle',
                'verbose_name_plural': 'Shackles',
                'ordering': ['working_load_limit'],
            },
        ),
        migrations.CreateModel(
            name='Thimble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the thimble in kg.', max_digits=10)),
                ('min_wire_rope_diameter', models.DecimalField(decimal_places=2, help_text='Minimum diameter of the wire rope in mm.', max_digits=10)),
                ('max_wire_rope_diameter', models.DecimalField(decimal_places=2, help_text='Maximum diameter of the wire rope in mm.', max_digits=10)),
                ('width_groove', models.DecimalField(decimal_places=2, help_text='Width of the groove in mm.', max_digits=10)),
                ('width_overall', models.DecimalField(decimal_places=2, help_text='Width of the overall sling in mm.', max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length of the thimble in mm.', max_digits=10)),
                ('length_inside', models.DecimalField(decimal_places=2, help_text='Length inside the thimble in mm.', max_digits=10)),
                ('width_inside', models.DecimalField(decimal_places=2, help_text='Width inside the thimble in mm.', max_digits=10)),
                ('thickness_back', models.DecimalField(decimal_places=2, help_text='Thickness of the back in mm.', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width of the thimble in mm.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Thimble',
                'verbose_name_plural': 'Thimbles',
                'ordering': ['min_wire_rope_diameter'],
            },
        ),
        migrations.CreateModel(
            name='WireRope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('construction_type', models.CharField(help_text='Construction type of the sling.', max_length=100)),
                ('material', models.CharField(choices=[('steel', 'Steel'), ('HMPE', 'HMPE'), ('aramid', 'Aramid'), ('other', 'Other')], help_text='Material of the sling.', max_length=100)),
                ('nominal_diameter', models.DecimalField(decimal_places=2, help_text='Nominal diameter in mm.', max_digits=10)),
                ('tensile_strength', models.DecimalField(decimal_places=3, help_text='Tensile strength in MPa.', max_digits=10)),
                ('minimum_breaking_load', models.DecimalField(decimal_places=3, help_text='Minimum breaking load in Te.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Wire Rope',
                'verbose_name_plural': 'Wire Ropes',
                'ordering': ['minimum_breaking_load'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the project.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the project.')),
                ('user', models.ForeignKey(help_text='User who created the project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiftingAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the analysis.', max_length=100)),
                ('maximum_gross_weight', models.FloatField()),
                ('location', models.CharField(help_text='Location of the lift analysis.', max_length=100)),
                ('configuration', models.JSONField()),
                ('lifting_points_qty', models.IntegerField()),
                ('results', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='main.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiggingDesign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrangement', models.JSONField()),
                ('results', models.JSONField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='main.liftinganalysis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the referenced sling', verbose_name='Sling ID')),
                ('configuration', models.CharField(choices=[('vertical', 'Vertical'), ('basket', 'Basket'), ('choke', 'Choke')], help_text='Configuration of the sling.', max_length=100)),
                ('termination', models.CharField(choices=[('hand splice', 'Hand Splice'), ('ferrule', 'Ferrule'), ('molten metal', 'Molten Metal'), ('resin poured sockets', 'Resin Poured Sockets')], help_text='Termination of the sling design_data.', max_length=100)),
                ('eye_type', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], help_text='Type of eye.', max_length=100)),
                ('content_type', models.ForeignKey(help_text='Type of sling (WireRope, Grommet, FibreSling)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Sling type')),
            ],
            options={
                'verbose_name': 'Sling Configuration',
                'verbose_name_plural': 'Sling Configurations',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='main_slingc_content_bb33fd_idx')],
                'unique_together': {('content_type', 'object_id', 'configuration', 'termination', 'eye_type')},
            },
        ),
    ]
