# Generated by Django 5.1.7 on 2025-09-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riggingdesign',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Convenience flag to mark the active/preferred design.'),
        ),
        migrations.AddField(
            model_name='riggingdesign',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Human-readable title for the design.', max_length=150),
        ),
        migrations.AddField(
            model_name='riggingdesign',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes or rationale.'),
        ),
        migrations.AddField(
            model_name='riggingdesign',
            name='project',
            field=models.ForeignKey(help_text='Project inherited from the linked analysis.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rigging_designs', to='main.project'),
        ),
        migrations.AddField(
            model_name='riggingdesign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', help_text='Lifecycle status of the design.', max_length=20),
        ),
        migrations.AddField(
            model_name='riggingdesign',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number of this design for the given analysis.'),
        ),
        migrations.AlterField(
            model_name='riggingdesign',
            name='analysis',
            field=models.ForeignKey(help_text='Lifting analysis this design design is based on.', on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='main.liftinganalysis'),
        ),
        migrations.AlterField(
            model_name='riggingdesign',
            name='arrangement',
            field=models.JSONField(help_text='Arrangement of selected components.'),
        ),
        migrations.AlterField(
            model_name='riggingdesign',
            name='results',
            field=models.JSONField(help_text='Full design results, including utilizations and factors.'),
        ),
        migrations.AlterUniqueTogether(
            name='riggingdesign',
            unique_together={('analysis', 'name', 'version')},
        ),
        migrations.AddIndex(
            model_name='riggingdesign',
            index=models.Index(fields=['analysis', 'project'], name='main_riggin_analysi_81e260_idx'),
        ),
    ]
