# Generated by Django 5.1.7 on 2025-10-08 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_riggingdesign_is_active_riggingdesign_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='riggingdesign',
            name='analysis',
            field=models.ForeignKey(help_text='Lifting analysis this design design is based on.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='main.liftinganalysis'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('company', models.CharField(blank=True, help_text='Company of the user.', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
