# Generated by Django 5.1.7 on 2026-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_riggingdesign_analysis_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liftinganalysis',
            name='lifting_points_qty',
            field=models.IntegerField(choices=[(1, '1 point'), (2, '2 points'), (3, '3 points'), (4, '4 points')]),
        ),
        migrations.AlterField(
            model_name='liftinganalysis',
            name='location',
            field=models.CharField(choices=[('offshore', 'Offshore'), ('onshore', 'Onshore'), ('inshore', 'Inshore'), ('subsea', 'Subsea')], help_text='Location of the lift analysis.', max_length=100),
        ),
    ]
