# Generated by Django 5.1.7 on 2026-02-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_liftinganalysis_lifting_points_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='owner',
        ),
    ]
