# Generated by Django 5.1.7 on 2026-02-16 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_user_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('company', models.CharField(blank=True, help_text='Company of the customer.', max_length=150)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], default='free', help_text='Customer subscription tier.', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer identifier.', max_length=100, null=True)),
                ('subscription_active', models.BooleanField(default=False, help_text='Whether the customer has an active paid subscription.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
