# Generated by Django 5.1.7 on 2026-02-16 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('stripe_event_id', models.CharField(db_index=True, help_text='Stripe event ID (e.g., evt_xxxxx) for idempotency.', max_length=100, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Stripe event type (e.g., customer.subscription.updated).', max_length=100)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Current processing status of this webhook.', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When processing started.', null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, help_text='When processing completed (success or failure).', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed.')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts.')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='Timestamp of last retry attempt.', null=True)),
                ('raw_payload', models.JSONField(help_text='Raw webhook payload from Stripe for debugging/replay.')),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update time.')),
                ('stripe_subscription_id', models.CharField(help_text='Stripe subscription ID (e.g., sub_xxxxx).', max_length=100, unique=True)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe product ID (e.g., prod_xxxxx).', max_length=100)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe price ID (e.g., price_xxxxx).', max_length=100)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='incomplete', help_text='Current subscription status from Stripe.', max_length=30)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], default='free', help_text='Subscription tier (maps from Stripe product metadata).', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of current billing period.', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of current billing period.', null=True)),
                ('trial_start', models.DateTimeField(blank=True, help_text='Trial start date.', null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='Trial end date.', null=True)),
                ('canceled_at', models.DateTimeField(blank=True, help_text='Timestamp when subscription was canceled.', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='If true, subscription will cancel at end of current period.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Timestamp when subscription ended.', null=True)),
                ('stripe_metadata', models.JSONField(blank=True, default=dict, help_text='Additional Stripe subscription metadata.')),
            ],
            options={
                'ordering': ['-current_period_end'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_data_last_synced',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful sync with Stripe.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional Stripe customer data for flexibility.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sync_error_message',
            field=models.TextField(blank=True, help_text='Error message from last failed sync attempt.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sync_status',
            field=models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('failed', 'Failed')], default='synced', help_text='Status of last Stripe data synchronization.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer identifier.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_active',
            field=models.BooleanField(default=False, help_text='Whether the customer has an active paid subscription. Cached from Subscription model.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], default='free', help_text='Cached customer subscription tier for fast queries. Source of truth is Subscription model.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['stripe_customer_id'], name='main_custom_stripe__bcccc0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tier', 'subscription_active'], name='main_custom_tier_7afd20_idx'),
        ),
        migrations.AddField(
            model_name='stripewebhookevent',
            name='related_customer',
            field=models.ForeignKey(blank=True, help_text='Related customer if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='main.customer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(help_text='Customer who owns this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main.customer'),
        ),
        migrations.AddField(
            model_name='stripewebhookevent',
            name='related_subscription',
            field=models.ForeignKey(blank=True, help_text='Related subscription if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='main.subscription'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='main_subscr_stripe__2fc7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'status'], name='main_subscr_custome_e3f7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='main_subscr_status_e9c443_idx'),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['stripe_event_id'], name='main_stripe_stripe__7c3f34_idx'),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['event_type', 'processing_status'], name='main_stripe_event_t_aa1142_idx'),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['processing_status', 'created_at'], name='main_stripe_process_9158ad_idx'),
        ),
    ]
