# Generated by Django 5.1.7 on 2026-03-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_stripewebhookevent_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripewebhookevent',
            name='related_customer',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='stripewebhookevent',
            name='related_subscription',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='StripeWebhookEvent',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
