from __future__ import annotations

from typing import Any, Dict, List


def _citations(*items: tuple[str, str]) -> List[Dict[str, str]]:
    return [
        {
            "reference_id": reference_id,
            "clause": clause,
        }
        for reference_id, clause in items
    ]


DESIGN_PARAMETER_SPECS: List[Dict[str, Any]] = [
    {
        "key": "static_hook_load",
        "label": "Static Hook Load",
        "category": "input",
        "context_path": ("static", "hook_load"),
        "unit_path": ("units", "load"),
        "variable_symbol": r"L_{\mathrm{hook,static}}",
    },
    {
        "key": "governing_static_sling_load",
        "label": "Governing Static Sling Load",
        "category": "input",
        "context_path": ("static", "controlling_sling_load"),
        "unit_path": ("units", "load"),
        "variable_symbol": r"L_{\mathrm{sling,static}}",
    },
    {
        "key": "dynamic_amplification_factor",
        "label": "Dynamic Amplification Factor",
        "category": "input",
        "context_path": ("dnv_factors", "dynamic_amplification_factor"),
        "variable_symbol": r"DAF",
    },
    {
        "key": "dynamic_hook_load",
        "label": "Dynamic Hook Load",
        "category": "input",
        "context_path": ("dynamic", "hook_load"),
        "unit_path": ("units", "load"),
        "variable_symbol": r"L_{\mathrm{hook,dyn}}",
    },
    {
        "key": "governing_dynamic_sling_load",
        "label": "Governing Dynamic Sling Load",
        "category": "input",
        "context_path": ("dynamic", "controlling_sling_load"),
        "unit_path": ("units", "load"),
        "variable_symbol": r"L_{\mathrm{sling,dyn}}",
    },
]


COMPONENT_TRACE_SPECS: Dict[str, List[Dict[str, Any]]] = {
    "Masterlink": [
        {
            "section": "inputs",
            "key": "WLL",
            "label": "Working Load Limit",
            "category": "input",
            "variable_symbol": r"WLL_{ML}",
        },
        {
            "section": "inputs",
            "key": "SWL",
            "label": "Safe Working Load",
            "category": "input",
            "variable_symbol": r"SWL_{ML}",
        },
        {
            "section": "inputs",
            "key": "manufacturer_safety_factor",
            "label": "Manufacturer Safety Factor",
            "category": "input",
            "variable_symbol": r"SF_{\mathrm{mfg}}",
        },
        {
            "section": "inputs",
            "key": "minimum_safety_factor",
            "label": "Minimum Safety Factor",
            "category": "input",
            "variable_symbol": r"SF_{\min}",
        },
        {
            "section": "inputs",
            "key": "DAF",
            "label": "Dynamic Amplification Factor",
            "category": "input",
            "variable_symbol": r"DAF",
        },
        {
            "section": "inputs",
            "key": "acting_load",
            "label": "Load Acting on Masterlink",
            "category": "input",
            "variable_symbol": r"L_{ML}",
        },
        {
            "section": "intermediates",
            "key": "proof_load",
            "label": "Proof Load",
            "category": "intermediate",
            "variable_symbol": r"PL_{ML}",
            "formula_latex": r"PL_{ML}=\begin{cases}2\cdot SWL_{ML},&SWL_{ML}\leq25\\1.22\cdot SWL_{ML}+20,&SWL_{ML}>25\end{cases}",
            "text_fallback": "PL = 2*SWL if SWL<=25 else 1.22*SWL+20",
            "citations": _citations(("1", "16.11.4")),
        },
        {
            "section": "intermediates",
            "key": "minimum_breaking_load",
            "label": "Minimum Breaking Load",
            "category": "intermediate",
            "variable_symbol": r"MBL_{ML}",
            "formula_latex": r"MBL_{ML}=SWL_{ML}\cdot SF_{\mathrm{mfg}}",
            "text_fallback": "MBL = SWL * SF_mfg",
        },
        {
            "section": "checks",
            "key": "UR1",
            "label": "Utilization Check 1",
            "category": "check",
            "variable_symbol": r"UR_{1,ML}",
            "formula_latex": r"UR_{1,ML}=\frac{L_{ML}\cdot SF_{\min}}{MBL_{ML}}",
            "text_fallback": "UR1 = Load * SF_min / MBL",
            "citations": _citations(("1", "16.5.2.6")),
        },
        {
            "section": "checks",
            "key": "UR2",
            "label": "Utilization Check 2",
            "category": "check",
            "variable_symbol": r"UR_{2,ML}",
            "formula_latex": r"UR_{2,ML}=\frac{L_{ML}}{SWL_{ML}\cdot DAF}",
            "text_fallback": "UR2 = Load / (SWL * DAF)",
            "citations": _citations(("1", "16.5.2.6")),
        },
        {
            "section": "checks",
            "key": "UR3",
            "label": "Utilization Check 3",
            "category": "check",
            "variable_symbol": r"UR_{3,ML}",
            "formula_latex": r"UR_{3,ML}=\frac{L_{ML}}{PL_{ML}}",
            "text_fallback": "UR3 = Load / ProofLoad",
            "citations": _citations(("1", "16.5.2.6")),
        },
        {
            "section": "results",
            "key": "utilization",
            "label": "Governing Utilization",
            "category": "result",
            "variable_symbol": r"UR_{ML}",
            "formula_latex": r"UR_{ML}=\max\left(UR_{1,ML},UR_{2,ML},UR_{3,ML}\right)",
            "text_fallback": "UR = max(UR1, UR2, UR3)",
            "citations": _citations(("1", "16.5.2.6")),
            "highlight_result": True,
        },
        {
            "section": "results",
            "key": "controlling_check",
            "label": "Controlling Check",
            "category": "note",
        },
    ],
    "Shackle": [
        {
            "section": "inputs",
            "key": "WLL",
            "label": "Working Load Limit",
            "category": "input",
            "variable_symbol": r"WLL_{SH}",
        },
        {
            "section": "inputs",
            "key": "SWL",
            "label": "Safe Working Load",
            "category": "input",
            "variable_symbol": r"SWL_{SH}",
        },
        {
            "section": "inputs",
            "key": "manufacturer_safety_factor",
            "label": "Manufacturer Safety Factor",
            "category": "input",
            "variable_symbol": r"SF_{\mathrm{mfg}}",
        },
        {
            "section": "inputs",
            "key": "minimum_safety_factor",
            "label": "Minimum Safety Factor",
            "category": "input",
            "variable_symbol": r"SF_{\min}",
        },
        {
            "section": "inputs",
            "key": "DAF",
            "label": "Dynamic Amplification Factor",
            "category": "input",
            "variable_symbol": r"DAF",
        },
        {
            "section": "inputs",
            "key": "acting_load",
            "label": "Load Acting on Shackle",
            "category": "input",
            "variable_symbol": r"L_{SH}",
        },
        {
            "section": "intermediates",
            "key": "proof_load",
            "label": "Proof Load",
            "category": "intermediate",
            "variable_symbol": r"PL_{SH}",
            "formula_latex": r"PL_{SH}=\begin{cases}2\cdot SWL_{SH},&SWL_{SH}\leq25\\1.22\cdot SWL_{SH}+20,&SWL_{SH}>25\end{cases}",
            "text_fallback": "PL = 2*SWL if SWL<=25 else 1.22*SWL+20",
            "citations": _citations(("1", "16.11.4")),
        },
        {
            "section": "intermediates",
            "key": "minimum_breaking_load",
            "label": "Minimum Breaking Load",
            "category": "intermediate",
            "variable_symbol": r"MBL_{SH}",
            "formula_latex": r"MBL_{SH}=SWL_{SH}\cdot SF_{\mathrm{mfg}}",
            "text_fallback": "MBL = SWL * SF_mfg",
        },
        {
            "section": "checks",
            "key": "UR1",
            "label": "Utilization Check 1",
            "category": "check",
            "variable_symbol": r"UR_{1,SH}",
            "formula_latex": r"UR_{1,SH}=\frac{L_{SH}\cdot SF_{\min}}{MBL_{SH}}",
            "text_fallback": "UR1 = Load * SF_min / MBL",
            "citations": _citations(("1", "16.5.2.6")),
        },
        {
            "section": "checks",
            "key": "UR2",
            "label": "Utilization Check 2",
            "category": "check",
            "variable_symbol": r"UR_{2,SH}",
            "formula_latex": r"UR_{2,SH}=\frac{L_{SH}}{SWL_{SH}\cdot DAF}",
            "text_fallback": "UR2 = Load / (SWL * DAF)",
            "citations": _citations(("1", "16.5.2.6")),
        },
        {
            "section": "checks",
            "key": "UR3",
            "label": "Utilization Check 3",
            "category": "check",
            "variable_symbol": r"UR_{3,SH}",
            "formula_latex": r"UR_{3,SH}=\frac{L_{SH}}{PL_{SH}}",
            "text_fallback": "UR3 = Load / ProofLoad",
            "citations": _citations(("1", "16.5.2.6")),
        },
        {
            "section": "results",
            "key": "utilization",
            "label": "Governing Utilization",
            "category": "result",
            "variable_symbol": r"UR_{SH}",
            "formula_latex": r"UR_{SH}=\max\left(UR_{1,SH},UR_{2,SH},UR_{3,SH}\right)",
            "text_fallback": "UR = max(UR1, UR2, UR3)",
            "citations": _citations(("1", "16.5.2.6")),
            "highlight_result": True,
        },
        {
            "section": "results",
            "key": "controlling_check",
            "label": "Controlling Check",
            "category": "note",
        },
    ],
    "MasterlinkAssembly": [
        {
            "section": "inputs",
            "key": "masterlink_load",
            "label": "Load Acting on Top Masterlink",
            "category": "input",
            "variable_symbol": r"L_{ML}",
        },
        {
            "section": "inputs",
            "key": "SWL_masterlink",
            "label": "Safe Working Load of Top Masterlink",
            "category": "input",
            "variable_symbol": r"SWL_{ML}",
        },
        {
            "section": "inputs",
            "key": "assembly_load",
            "label": "Load Acting on Sub-Link",
            "category": "input",
            "variable_symbol": r"L_{SL}",
        },
        {
            "section": "inputs",
            "key": "SWL_assembly",
            "label": "Safe Working Load of Sub-Link",
            "category": "input",
            "variable_symbol": r"SWL_{SL}",
        },
        {
            "section": "inputs",
            "key": "SF_mfg",
            "label": "Manufacturer Safety Factor",
            "category": "input",
            "variable_symbol": r"SF_{\mathrm{mfg}}",
        },
        {
            "section": "inputs",
            "key": "SF_min",
            "label": "Minimum Safety Factor",
            "category": "input",
            "variable_symbol": r"SF_{\min}",
        },
        {
            "section": "inputs",
            "key": "DAF",
            "label": "Dynamic Amplification Factor",
            "category": "input",
            "variable_symbol": r"DAF",
        },
        {
            "section": "intermediates",
            "key": "proof_load_masterlink",
            "label": "Top Masterlink Proof Load",
            "category": "intermediate",
            "variable_symbol": r"PL_{ML}",
            "formula_latex": r"PL_{ML}=\begin{cases}2\cdot SWL_{ML},&SWL_{ML}\leq25\\1.22\cdot SWL_{ML}+20,&SWL_{ML}>25\end{cases}",
            "text_fallback": "PL = 2*SWL if SWL<=25 else 1.22*SWL+20",
            "citations": _citations(("1", "16.11.4")),
        },
        {
            "section": "intermediates",
            "key": "MBL_masterlink",
            "label": "Top Masterlink Minimum Breaking Load",
            "category": "intermediate",
            "variable_symbol": r"MBL_{ML}",
            "formula_latex": r"MBL_{ML}=SWL_{ML}\cdot SF_{\mathrm{mfg}}",
            "text_fallback": "MBL = SWL * SF_mfg",
        },
        {
            "section": "checks",
            "key": "UR_masterlink",
            "label": "Top Masterlink Utilization Check",
            "category": "check",
            "variable_symbol": r"UR_{ML}",
            "formula_latex": r"UR_{ML}=\max\left(\frac{L_{ML}\cdot SF_{\min}}{MBL_{ML}},\frac{L_{ML}}{SWL_{ML}\cdot DAF},\frac{L_{ML}}{PL_{ML}}\right)",
            "text_fallback": "UR_ML = max(Load * SF_min / MBL, Load / (SWL * DAF), Load / ProofLoad)",
            "citations": _citations(("1", "16.5.2.6")),
        },
        {
            "section": "intermediates",
            "key": "proof_load_assembly",
            "label": "Sub-Link Proof Load",
            "category": "intermediate",
            "variable_symbol": r"PL_{SL}",
            "formula_latex": r"PL_{SL}=\begin{cases}2\cdot SWL_{SL},&SWL_{SL}\leq25\\1.22\cdot SWL_{SL}+20,&SWL_{SL}>25\end{cases}",
            "text_fallback": "PL = 2*SWL if SWL<=25 else 1.22*SWL+20",
            "citations": _citations(("1", "16.11.4")),
        },
        {
            "section": "intermediates",
            "key": "MBL_assembly",
            "label": "Sub-Link Minimum Breaking Load",
            "category": "intermediate",
            "variable_symbol": r"MBL_{SL}",
            "formula_latex": r"MBL_{SL}=SWL_{SL}\cdot SF_{\mathrm{mfg}}",
            "text_fallback": "MBL = SWL * SF_mfg",
        },
        {
            "section": "checks",
            "key": "UR_assembly",
            "label": "Sub-Link Utilization Check",
            "category": "check",
            "variable_symbol": r"UR_{SL}",
            "formula_latex": r"UR_{SL}=\max\left(\frac{L_{SL}\cdot SF_{\min}}{MBL_{SL}},\frac{L_{SL}}{SWL_{SL}\cdot DAF},\frac{L_{SL}}{PL_{SL}}\right)",
            "text_fallback": "UR_SL = max(Load * SF_min / MBL, Load / (SWL * DAF), Load / ProofLoad)",
            "citations": _citations(("1", "16.5.2.6")),
        },
        {
            "section": "results",
            "key": "utilization",
            "label": "Governing Utilization",
            "category": "result",
            "variable_symbol": r"UR_{MLA}",
            "formula_latex": r"UR_{MLA}=\max\left(UR_{ML},UR_{SL}\right)",
            "text_fallback": "UR_MLA = max(UR_ML, UR_SL)",
            "citations": _citations(("1", "16.5.2.6")),
            "highlight_result": True,
        },
        {
            "section": "results",
            "key": "controlling",
            "label": "Controlling Component",
            "category": "note",
        },
    ],
    "WireRope": [
        {
            "section": "inputs",
            "key": "acting_load",
            "label": "Design Load",
            "category": "input",
            "variable_symbol": r"L_{WR}",
        },
        {
            "section": "inputs",
            "key": "MBL",
            "label": "Minimum Breaking Load",
            "category": "input",
            "variable_symbol": r"MBL_{WR}",
        },
        {
            "section": "inputs",
            "key": "wire_diameter",
            "label": "Wire Diameter",
            "category": "input",
            "variable_symbol": r"d_{WR}",
        },
        {
            "section": "inputs",
            "key": "min_bending_diameter",
            "label": "Minimum Bending Diameter",
            "category": "input",
            "variable_symbol": r"D_{\min}",
        },
        {
            "section": "inputs",
            "key": "configuration",
            "label": "Configuration",
            "category": "input",
            "variable_symbol": r"C_{\mathrm{cfg}}",
        },
        {
            "section": "inputs",
            "key": "eye_type",
            "label": "Eye Type",
            "category": "input",
            "variable_symbol": r"T_{\mathrm{eye}}",
        },
        {
            "section": "inputs",
            "key": "termination",
            "label": "Termination",
            "category": "input",
            "variable_symbol": r"T_{\mathrm{term}}",
        },
        {
            "section": "inputs",
            "key": "material",
            "label": "Material",
            "category": "input",
            "variable_symbol": r"M_{\mathrm{mat}}",
        },
        {
            "section": "factors",
            "key": "config_factor",
            "label": "Configuration Factor",
            "category": "factor",
            "variable_symbol": r"F_{\mathrm{cfg}}",
        },
        {
            "section": "factors",
            "key": "lifting_factor",
            "label": "Lifting Factor",
            "category": "factor",
            "variable_symbol": r"F_{\mathrm{lift}}",
        },
        {
            "section": "factors",
            "key": "consequence_factor",
            "label": "Consequence Factor",
            "category": "factor",
            "variable_symbol": r"F_{\mathrm{cons}}",
        },
        {
            "section": "factors",
            "key": "wear_factor",
            "label": "Wear Factor",
            "category": "factor",
            "variable_symbol": r"F_{\mathrm{wear}}",
        },
        {
            "section": "factors",
            "key": "material_factor",
            "label": "Material Factor",
            "category": "factor",
            "variable_symbol": r"F_{\mathrm{mat}}",
        },
        {
            "section": "factors",
            "key": "termination_factor",
            "label": "Termination Factor",
            "category": "factor",
            "variable_symbol": r"F_{\mathrm{term}}",
        },
        {
            "section": "factors",
            "key": "eye_bending_factor",
            "label": "Eye Bending Factor",
            "category": "factor",
            "variable_symbol": r"F_{\mathrm{eye}}",
        },
        {
            "section": "factors",
            "key": "config_bending_factor",
            "label": "Configuration Bending Factor",
            "category": "factor",
            "variable_symbol": r"F_{\mathrm{bend,cfg}}",
        },
        {
            "section": "factors",
            "key": "governing_bending_factor",
            "label": "Governing Bending Factor",
            "category": "factor",
            "variable_symbol": r"F_{\mathrm{bend,gov}}",
        },
        {
            "section": "intermediates",
            "key": "D_over_d",
            "label": "D over d Ratio",
            "category": "intermediate",
            "variable_symbol": r"\frac{D}{d}",
            "formula_latex": r"\frac{D}{d}=\frac{D_{\min}}{d_{WR}}",
            "text_fallback": "D/d = min_bending_diameter / wire_diameter",
        },
        {
            "section": "intermediates",
            "key": "nominal_safety_factor",
            "label": "Nominal Safety Factor",
            "category": "intermediate",
            "variable_symbol": r"NSF_{\mathrm{nom}}",
            "formula_latex": r"NSF_{\mathrm{nom}}=\max\left(F_{\mathrm{lift}}\cdot F_{\mathrm{cons}}\cdot\max(F_{\mathrm{term}},F_{\mathrm{bend,gov}})\cdot F_{\mathrm{mat}}\cdot F_{\mathrm{wear}},2.3\cdot\max(F_{\mathrm{term}},F_{\mathrm{bend,gov}})\cdot F_{\mathrm{wear}}\right)",
            "text_fallback": "Nominal safety factor derived from lifting, consequence, termination, bending, material, and wear factors.",
            "citations": _citations(("1", "16.4.8")),
        },
        {
            "section": "intermediates",
            "key": "effective_MBL",
            "label": "Effective Minimum Breaking Load",
            "category": "intermediate",
            "variable_symbol": r"MBL_{\mathrm{eff}}",
            "formula_latex": r"MBL_{\mathrm{eff}}=MBL_{WR}\cdot F_{\mathrm{cfg}}",
            "text_fallback": "Effective MBL = MBL * configuration factor",
        },
        {
            "section": "results",
            "key": "utilization",
            "label": "Governing Utilization",
            "category": "result",
            "variable_symbol": r"UR_{WR}",
            "formula_latex": r"UR_{WR}=\frac{L_{WR}\cdot NSF_{\mathrm{nom}}}{MBL_{\mathrm{eff}}}",
            "text_fallback": "UR_WR = Load * NSF_nom / MBL_eff",
            "citations": _citations(("1", "16.5.2.6")),
            "highlight_result": True,
        },
    ],
}


def get_component_trace_specs(component_type: str | None) -> List[Dict[str, Any]]:
    if not component_type:
        return []
    return COMPONENT_TRACE_SPECS.get(component_type, [])
