REQUIRED_MASTERLINK_ASSEMBLY_HEADERS = ['MANUFACTURER', 'MODEL', 'TYPE', 'WORKING LOAD LIMIT', 'WEIGHT', 'SAFETY FACTOR', 'DIAMETER', 'LENGTH INSIDE', 'WIDTH INSIDE', 'ASSEMBLY DIAMETER', 'ASSEMBLY LENGTH INSIDE', 'ASSEMBLY WIDTH INSIDE']

REQUIRED_MASTERLINK_HEADERS = ['MANUFACTURER', 'MODEL', 'TYPE', 'WORKING LOAD LIMIT', 'WEIGHT', 'SAFETY FACTOR', 'DIAMETER', 'LENGTH INSIDE', 'WIDTH INSIDE']

REQUIRED_SHACKLE_HEADERS = ['MANUFACTURER', 'MODEL', 'WORKING LOAD LIMIT', 'WEIGHT', 'SAFETY FACTOR', 'INSIDE WIDTH', 'INSIDE LENGTH', 'BOW WIDTH', 'LENGTH', 'WIDTH', 'BOW DIAMETER', 'EYE DIAMETER', 'PIN DIAMETER', 'BOLT LENGTH', 'TOLERANCE INSIDE WIDTH', 'TOLERANCE INSIDE LENGTH']

REQUIRED_WIRE_ROPE_HEADERS =['SLING TYPE', 'CONSTRUCTION TYPE', 'MATERIAL', 'NOMINAL DIAMETER', 'TENSILE STRENGTH', 'MINIMUM BREAKING LOAD']

REQUIRED_THIMBLE_HEADERS = ['WEIGHT', 'MIN WIRE ROPE DIAMETER', 'MAX WIRE ROPE DIAMETER', 'WIDTH GROOVE', 'WIDTH OVERALL', 'LENGTH', 'LENGTH INSIDE', 'WIDTH INSIDE', 'THICKNESS BACK', 'WIDTH']