@analysis_id = de44ede8-533c-49f5-a290-685352851e10

### Login
POST {{host}}/api/v1/auth/login/
Content-Type: application/json

{
  "email": "{{first_username}}",
  "password": "{{first_password}}"
}

> {%
    client.global.set("access_token", response.body.access);
%}

###
GET {{host}}/api/v1/design/?analysis_id={{analysis_id}}
Authorization: Bearer {{access_token}}
